name: task_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.20.2
  cloud_firestore: ^5.6.3
  cloud_functions: ^5.2.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.6.2
  firebase_storage: ^12.0.0
  connectivity_plus: ^6.1.1
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  pdf: ^3.11.0
  printing: ^5.12.0
  image_picker: ^1.1.0
  path_provider: ^2.1.3
  sqflite: ^2.3.0
  path: any




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
        - asset: assets/fonts/NotoSansBengali-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
